/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jaint;

import jaint.formas.Elipse;
import jaint.formas.Retangulo;
import jaint.formas.Linha;
import jaint.formas.Forma;
import jaint.formas.Poligono;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author r2leyser
 */
public class JanelaPrincipal extends javax.swing.JFrame {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName());

	private Forma forma;

	/**
	 * Creates new form JanelaPrincipal
	 */
	public JanelaPrincipal() {
		initComponents();
	} 

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup = new javax.swing.ButtonGroup();
                jMenu1 = new javax.swing.JMenu();
                painelDesenho = new jaint.PainelDesenho();
                PainelFormas = new javax.swing.JPanel();
                btnLinha = new javax.swing.JToggleButton();
                btnPoligono = new javax.swing.JToggleButton();
                btnRet = new javax.swing.JToggleButton();
                btnElipse = new javax.swing.JToggleButton();
                pnlContorno = new javax.swing.JPanel();
                pnlPreenchimento = new javax.swing.JPanel();
                txtPolyInput = new javax.swing.JFormattedTextField();

                jMenu1.setText("jMenu1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Jaint");

                painelDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                painelDesenhoMouseDragged(evt);
                        }
                });
                painelDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                painelDesenhoMousePressed(evt);
                        }
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                painelDesenhoMouseReleased(evt);
                        }
                });

                javax.swing.GroupLayout painelDesenhoLayout = new javax.swing.GroupLayout(painelDesenho);
                painelDesenho.setLayout(painelDesenhoLayout);
                painelDesenhoLayout.setHorizontalGroup(
                        painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 838, Short.MAX_VALUE)
                );
                painelDesenhoLayout.setVerticalGroup(
                        painelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 524, Short.MAX_VALUE)
                );

                PainelFormas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Formas"));

                buttonGroup.add(btnLinha);
                btnLinha.setSelected(true);
                btnLinha.setText("Linha");
                btnLinha.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLinhaActionPerformed(evt);
                        }
                });

                buttonGroup.add(btnPoligono);
                btnPoligono.setText("Poligono");

                buttonGroup.add(btnRet);
                btnRet.setText("Retângulo");

                buttonGroup.add(btnElipse);
                btnElipse.setText("Elipse");

                pnlContorno.setBackground(new java.awt.Color(0, 0, 0));
                pnlContorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pnlContorno.setPreferredSize(new java.awt.Dimension(20, 20));
                pnlContorno.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                pnlContornoMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlContornoLayout = new javax.swing.GroupLayout(pnlContorno);
                pnlContorno.setLayout(pnlContornoLayout);
                pnlContornoLayout.setHorizontalGroup(
                        pnlContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
                );
                pnlContornoLayout.setVerticalGroup(
                        pnlContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
                );

                pnlPreenchimento.setBackground(new java.awt.Color(0, 0, 0));
                pnlPreenchimento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                pnlPreenchimento.setPreferredSize(new java.awt.Dimension(20, 20));
                pnlPreenchimento.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                pnlPreenchimentoMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlPreenchimentoLayout = new javax.swing.GroupLayout(pnlPreenchimento);
                pnlPreenchimento.setLayout(pnlPreenchimentoLayout);
                pnlPreenchimentoLayout.setHorizontalGroup(
                        pnlPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
                );
                pnlPreenchimentoLayout.setVerticalGroup(
                        pnlPreenchimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
                );

                txtPolyInput.setText("5");
                txtPolyInput.setMinimumSize(new java.awt.Dimension(200, 24));
                txtPolyInput.setPreferredSize(new java.awt.Dimension(200, 24));

                javax.swing.GroupLayout PainelFormasLayout = new javax.swing.GroupLayout(PainelFormas);
                PainelFormas.setLayout(PainelFormasLayout);
                PainelFormasLayout.setHorizontalGroup(
                        PainelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelFormasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElipse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPoligono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPolyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                PainelFormasLayout.setVerticalGroup(
                        PainelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PainelFormasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btnLinha)
                                .addComponent(btnRet)
                                .addComponent(btnElipse)
                                .addComponent(pnlContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnlPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPoligono)
                                .addComponent(txtPolyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PainelFormas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PainelFormas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void painelDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMousePressed
		if (btnLinha.isSelected()) {
			forma = new Linha();
		} else if (btnRet.isSelected()) {
			forma = new Retangulo();
		} else if (btnElipse.isSelected()){
			forma = new Elipse();
		} else if (btnPoligono.isSelected()){
			forma = new Poligono(
				Integer.parseInt(txtPolyInput.getText())
			);

		}
		
		forma.setContorno(pnlContorno.getBackground());
		forma.setPreenchimento(pnlPreenchimento.getBackground());
		forma.setX1(evt.getX());
		forma.setY1(evt.getY());
        }//GEN-LAST:event_painelDesenhoMousePressed

        private void painelDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseReleased
		forma.setX2(evt.getX());
		forma.setY2(evt.getY());
		painelDesenho.addForma(forma);
		painelDesenho.setFormaTemp(null);
		painelDesenho.repaint();
        }//GEN-LAST:event_painelDesenhoMouseReleased

        private void painelDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelDesenhoMouseDragged
		forma.setContorno(pnlContorno.getBackground());
		forma.setX2(evt.getX());
		forma.setY2(evt.getY());
		painelDesenho.setFormaTemp(forma);
		painelDesenho.repaint();
        }//GEN-LAST:event_painelDesenhoMouseDragged

        private void btnLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinhaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnLinhaActionPerformed

        private void pnlContornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlContornoMouseClicked
                Color c = JColorChooser.showDialog(this, "Cor do Contorno", pnlContorno.getBackground());
		
		if ( c != null) {
			pnlContorno.setBackground(c);
		}
        }//GEN-LAST:event_pnlContornoMouseClicked

        private void pnlPreenchimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPreenchimentoMouseClicked
                Color c = JColorChooser.showDialog(this, "Cor do Preenchimento", pnlContorno.getBackground());
		
		if ( c != null) {
			pnlPreenchimento.setBackground(c);
		}
        }//GEN-LAST:event_pnlPreenchimentoMouseClicked

	public static void main(String[] args) {
		JanelaPrincipal janela = new JanelaPrincipal();
		janela.setVisible(true);
	}
		

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel PainelFormas;
        private javax.swing.JToggleButton btnElipse;
        private javax.swing.JToggleButton btnLinha;
        private javax.swing.JToggleButton btnPoligono;
        private javax.swing.JToggleButton btnRet;
        private javax.swing.ButtonGroup buttonGroup;
        private javax.swing.JMenu jMenu1;
        private jaint.PainelDesenho painelDesenho;
        private javax.swing.JPanel pnlContorno;
        private javax.swing.JPanel pnlPreenchimento;
        private javax.swing.JFormattedTextField txtPolyInput;
        // End of variables declaration//GEN-END:variables
}
